Incremental optimization
grandivory/mods-optimizer pull request #30
Opened 2021-06-17 03:50 UTC by DylanTusler

This is provided as a working POC for the change to improve remodding workflow by allowing users to work down their priority list toon by toon and trigger optimizations from within the character edit form directly.

Very much a first draft, more arse than class.

This PR does the following things:
1. Expose missed targets on the CharacterEditForm for quick reference.
2. Add a "Save and Run" button to the character edit form that saves the current targets and runs an "incremental" optimization (i.e. only up to the currently viewed character.)

I would like for the CharacterEditForm to remain open and updated missed targets info to be displayed, but haven't managed to work that out. For now you can see what the intention is.

2021-06-17 03:54 UTC, DylanTusler commented
![image](https://user-images.githubusercontent.com/11711132/122328744-81c08a80-cf73-11eb-9d8b-ff59a7b8ab9c.png)

2021-06-17 11:35 UTC, DylanTusler commented
@grandivory I've added more changes this evening (my time) and this is a lot closer to fully functional now. I've loaded in my data from a real run and found it awesome for finding mod combinations that I normally wouldn't persist to discover.

The latest push includes these changes:
1. Save and Run button now always present on CharacterEditForm
2. It works! If you click it, it will run up to that character in the optimizer, and update the missed targets.
3. Full optimization still works.

The following still needs fixing:
1. If you do an incremental mod update, you have to click "Save" to exit the characterEditForm once you are done. If you click "Cancel" then full optimization doesn't work. This is because the profile.stopAt value is only reset when clicking "Save" not "Cancel". I have not worked out how to reset it when clicking Cancel as all the Cancel does right now is hide the modal.
2. Optimization information modals are suppressed by the incremental validation, which means if you skip down to a character that is AFTER one with optimize targets, the optimization will take a long time, but there is no visual feedback that it is slow because of the optimized target in between. I'd like some kind of visual feedback why the optimization is taking a long time but couldn't work out how to put a second modal over the CharacterEditForm.

2021-06-17 11:36 UTC, DylanTusler commented
Here's a video demonstrating me quickly finding my mod targets with OB. It would have been really really hard to do this the old way, especially experimenting with mod sets.

https://user-images.githubusercontent.com/11711132/122389110-ee5b7980-cfb3-11eb-83d3-9507dfad250f.mp4

2021-06-17 19:24 UTC, grandivory requested changes
This is looking really good. I'm happy to make the requested changes myself if you'd like, or you can keep working on it. I'll merge the changes in once you mark the PR as ready for review.

2021-06-17 19:24 UTC, grandivory commented on public/workers/optimizer.js
> +      const stopAt = profile.stopAt;
Since the optimizer still supports having multiple of the same character within the selected characters list, `stopAt` should be the index of the last character to optimize, rather than the character ID.

When the property is renamed, it would also be nice to have it be something a little more mathematically descriptive, like `characterLimit`, or something along those lines.

2021-06-17 19:24 UTC, grandivory commented on public/workers/optimizer.js
>    const optimizerResults = order.reduce((modSuggestions, { id: characterID, target }, index) => {
When `stopAt` is the last index rather than a character ID, this can be greatly simplified. You don't even need to have a variable for whether to break anymore, you could just do something like:

```suggestion
  const optimizerResults = order.slice(0, limit).reduce((modSuggestions, { id: characterID, target }, index) => {
```

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    dispatch(finishEditCharacterTarget(characterIndex, target, close));
Rather than have `close` be an argument to `finishEditCharacterTarget`, I'd rather break it up further to just have two actions - one that saves the new target, and one that cleans up and closes out the modal.

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +  targets (missedGoals) {
This should be renamed to something a little more descriptive, especially since the modal already has a `targets` section in it. Maybe something like `missedReportTargets`, or something along those lines?

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    const targetStatRows =  missedGoals && missedGoals.map((missedGoal, index) =>
Because you already have the early return on the line above, you don't need to duplicate the null check here.

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +            {this.targets(this.props.modAssignments.filter(x => x && x.id && x.id === character.baseID)[0]?.missedGoals)}
The `x.id` check here is superfluous - if it doesn't exist, it will return `undefined`, which won't match `character.baseID` anyway.

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    <div className={'form-row'} key={index}>
It would be nice to take this whole section and label / separate it from the form above somehow. Maybe something along the lines of what I have in the auto-generate list modal, except not collapsible?

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    const targetStatRows =  missedGoals && missedGoals.map((missedGoal, index) =>
Since `missedGoal` is itself a tuple, it might be nice to break it out into variables so that you don't need to keep indexing it. Something like:

```suggestion
    const targetStatRows =  missedGoals && missedGoals.map(([targetStat, resultValue], index) =>
```

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +        <button type={'button'} onClick={() => this.runCalc()}>Save and Run</button>
```suggestion
        <button type={'button'} onClick={() => this.runCalc()}>Save and Re-run</button>
```

2021-06-17 19:24 UTC, grandivory commented on src/containers/CharacterEditView/CharacterEditView.js
> +          // this.props.profile.stopAt = "";
This can be solved by creating an action in `state/actions/characterEdit.js` to `updateStopAt...` (or something similar) and calling it here with `dispatch`. If you look at other actions in there, you'll see I already have an `updateProfile` helper function where all you have to do is return the new profile to store.

2021-06-17 19:24 UTC, grandivory commented on src/domain/OptimizerRun.js
> +  stopAt;
This shouldn't actually be needed on this class. `stopAt` is more of a behavioral marker on how an optimization gets run. A given `OptimizationRun` will already have all the required data, since if a run were passed a `stopAt` value, then the characters beyond simply won't exist.

2021-06-17 19:24 UTC, grandivory commented on src/domain/PlayerProfile.js
> +      profileJson.stopAt || ""
You can just put the default here. This is only called for old versions of the profile, which will never have `stopAt` defined.

2021-06-21 23:10 UTC, DylanTusler commented on public/workers/optimizer.js
> +      const stopAt = profile.stopAt;
lol, yeah I agree. I will come up with something a bit more readable.

2021-06-22 04:09 UTC, DylanTusler commented on public/workers/optimizer.js
> +      const stopAt = profile.stopAt;
@grandivory what do you think I should use as a "no limit" value? Would you go with -1 or undefined?

2021-06-22 15:07 UTC, grandivory commented on public/workers/optimizer.js
> +      const stopAt = profile.stopAt;
I'd use null or undefined.

2021-06-27 22:21 UTC, DylanTusler commented on public/workers/optimizer.js
> +      const stopAt = profile.stopAt;
lol finally came back to read this, and I've gone with -1. However, it kind of made sense in the context. Anyway, I've pushed this change now. Trying to get some stuff done before work today while I'm fresh.

2021-06-27 22:21 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +  targets (missedGoals) {
Done

2021-06-27 22:24 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    const targetStatRows =  missedGoals && missedGoals.map((missedGoal, index) =>
Nice yeah done this too.

2021-06-27 22:49 UTC, DylanTusler commented on src/containers/CharacterEditView/CharacterEditView.js
> +          // this.props.profile.stopAt = "";
This is done now

2021-06-27 22:49 UTC, DylanTusler commented on src/domain/PlayerProfile.js
> +      profileJson.stopAt || ""
Done

2021-06-27 22:51 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +        <button type={'button'} onClick={() => this.runCalc()}>Save and Run</button>
I changed the button text in the meanwhile, but I think the whole area needs some cosmetic work. Feel free to make whatever changes you want. I was focused on function. Presentation is DEFINITELY not my thing.

2021-06-27 22:51 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    dispatch(finishEditCharacterTarget(characterIndex, target, close));
Can I leave this to you? This is a function that calls a function that calls a function etc. Was making me a little wary to mess with it.

2021-06-27 22:52 UTC, DylanTusler commented on public/workers/optimizer.js
>    const optimizerResults = order.reduce((modSuggestions, { id: characterID, target }, index) => {
I have simplified this, not quite this way, because I still want to push null suggestedMods for all the characters after the selected one, but I am using an index now so it works for multiple occurrences of the same character.

2021-06-27 22:55 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    const targetStatRows =  missedGoals && missedGoals.map((missedGoal, index) =>
Done

2021-06-27 22:55 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +            {this.targets(this.props.modAssignments.filter(x => x && x.id && x.id === character.baseID)[0]?.missedGoals)}
I think I fixed this too

2021-06-27 22:56 UTC, DylanTusler commented on src/containers/CharacterEditForm/CharacterEditForm.js
> +    <div className={'form-row'} key={index}>
Can I leave the cosmetics to you? I am terrible at this kind of stuff. You would end up redoing all my work in this area anyway.

2021-06-27 23:06 UTC, DylanTusler commented
@grandivory I think I am done for now. I have left a couple of your requests, as mentioned above. Also I have not done the progress bar thing I wanted to do as yet, but I think it is a nice-to-have rather than an essential piece. I wanted to give you plenty of time to check it over before the next TW remodding stuff kicks off.

2021-06-27 23:15 UTC, DylanTusler commented on src/domain/OptimizerRun.js
> +  stopAt;
This is done now.

2021-07-05 16:53 UTC, merged